//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKeZone3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BK_DiaBan
    {
        public string MaXa { get; set; }
        public string MaThon { get; set; }
        public string MaDiaBan { get; set; }
        public string TenDiaBan { get; set; }
        public Nullable<bool> IsDiaBanMau { get; set; }
    }
}
