//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKeZone3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BK_Ho
    {
        public string IdHo { get; set; }
        public Nullable<double> Latitude_V { get; set; }
        public Nullable<double> Longitude_K { get; set; }
        public string SttNha { get; set; }
        public string SttHo { get; set; }
        public int TTNT { get; set; }
        public string TenChuHo { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public int TongSoNguoi { get; set; }
        public int TongSoNu { get; set; }
        public Nullable<bool> IsWebForm { get; set; }
        public Nullable<bool> IsHoMau { get; set; }
        public string GhiChu { get; set; }
    }
}
