//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKeZone3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_DanhSachChucNang
    {
        public int MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public string TenForm { get; set; }
    }
}
