//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKeZone3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QT_SystemLog
    {
        public int IdLog { get; set; }
        public string MaNguoiDung { get; set; }
        public Nullable<System.DateTime> DateLog { get; set; }
        public string MyFunction { get; set; }
        public string MyAction { get; set; }
        public string MyObject { get; set; }
    }
}
